module.exports = {
  STUDY_ROOM_MAX_STUDENTS: 10,
  STUDY_ROOM_JOIN_CREDIT: 20,
  STUDY_ROOM_CREATE_CREDIT: 50,
  STUDY_ROOM_TEACHER_CREDIT_RATE: 0.7,
  STUDY_ROOM_TEACHER_POINT_RATE: 0.7,
  STUDY_ROOM_TEACHER_SESSION_MS: 60 * 60 * 1000,
  STUDY_ROOM_MONTH_MS: 30 * 24 * 60 * 60 * 1000,
  ROOM_QUIZ_ATTEND_CREDIT: 20,
  ROOM_QUIZ_REWARD_POOL_RATE: 0.7,
  ROOM_QUIZ_MAX_QUESTIONS: 30,
  PUBLIC_QUIZ_ATTEND_CREDIT: 20,
  PUBLIC_QUIZ_REWARD_POOL_RATE: 0.7,
  PUBLIC_QUIZ_MAX_QUESTIONS: 30,
  PUBLIC_QUIZ_REWARD_STEP_SIZE: 50,
  PUBLIC_QUIZ_REWARD_BASE_WINNERS: 10,
  PUBLIC_QUIZ_REWARD_WINNER_STEP: 5,
  PUBLIC_QUIZ_REWARD_MAX_WINNERS: 30,
  COURSE_MARKETPLACE_COMMISSION_RATE: 0.2,
  COURSE_TEACHER_POOL_RATE: 0.8,
  TEACHER_WITHDRAW_EARNING_RATE: 0.8,
  TEACHER_WITHDRAW_PLATFORM_BONUS_RATE: 0.1,
  TEACHER_WITHDRAW_PLATFORM_PROFIT_RATE: 0.1,
  TEACHER_QUALITY_MAX_BONUS_RATE: 0.15,
  TEACHER_QUALITY_MAX_PENALTY_RATE: 0.15,
  TEACHER_QUALITY_REPLY_FAST_MINUTES: 10,
  TEACHER_QUALITY_REPLY_OK_MINUTES: 60,
  TEACHER_QUALITY_REPLY_LATE_MINUTES: 6 * 60,
  TEACHER_QUALITY_REACTION_DELTAS: {
    helpful: 0.2,
    clear: 0.2,
    thanks: 0.15,
    liked: 0.2,
    disliked: -0.25,
    confusing: -0.25,
  },
  TEACHER_QUALITY_RATING_DELTAS: {
    5: 1,
    4: 0.35,
    3: 0,
    2: -1,
    1: -1.5,
  },
  TEACHER_QUALITY_SOURCE_CAPS: {
    chat_reaction: 8,
    first_reply_speed: 10,
    quiz_rating: 20,
    call_review: 20,
    course_session_rating: 20,
  },
  COURSE_PERFORMANCE_WEIGHTS: {
    classesTaken: 0.5,
    ratings: 0.2,
    completionOnTime: 0.2,
    monthlyQuiz: 0.05,
    resourcesShared: 0.05,
  },
  TEACHER_EXPERIENCE_LEVELS: [
    { level: 1, points: 0 },
    { level: 2, points: 400 },
    { level: 3, points: 1000 },
    { level: 4, points: 1500 },
    { level: 5, points: 2500 },
    { level: 6, points: 4000 },
    { level: 7, points: 6000 },
    { level: 8, points: 8000 },
    { level: 9, points: 10000 },
    { level: 10, points: 15000 },
    { level: 11, points: 20000 },
    { level: 12, points: 30000 },
  ],
  REFERRAL_REWARD_CREDIT: 50,
  REFERRAL_REWARD_DURATION_HOURS: 1,
};
