module.exports = {
  STUDY_ROOM_MAX_STUDENTS: 10,
  STUDY_ROOM_JOIN_CREDIT: 20,
  STUDY_ROOM_CREATE_CREDIT: 50,
  STUDY_ROOM_TEACHER_CREDIT_RATE: 0.7,
  STUDY_ROOM_TEACHER_POINT_RATE: 0.7,
  STUDY_ROOM_TEACHER_SESSION_MS: 60 * 60 * 1000,
  STUDY_ROOM_MONTH_MS: 30 * 24 * 60 * 60 * 1000,
  REFERRAL_REWARD_CREDIT: 50,
  REFERRAL_REWARD_DURATION_HOURS: 1,
};
